# Generated by Django 4.2.16 on 2024-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(default='blog1.jpg', upload_to='blog_images/')),
                ('titulo', models.CharField(max_length=200)),
                ('noticia', models.CharField(max_length=100000)),
            ],
        ),
    ]
